# Generated by Django 2.2.19 on 2021-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=13)),
                ('stock_quantity', models.IntegerField(default=None)),
                ('volume', models.FloatField(editable=False)),
            ],
        ),
    ]
