# Generated by Django 2.2.19 on 2021-03-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
